apiVersion: v1
kind: Service
metadata:
  name: mint-service
spec:
  selector:
    app: mint-server
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mint-server
spec:
  selector:
    matchLabels:
      app: mint-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mint-server
    spec:
      containers:
      - name: mint-server
        image: registry.gitlab.com/mattesilver/mint:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: gitlab-docker-creds
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "mint.dev.oeklo.at"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        
        backend:
          service:
            name: mint-service
            port:
              number: 8000
